@startuml
class Comment {
    + Content : string <<get>> <<set>>
    + HasBeenEdited : bool <<get>> <<set>>
    + IsDeleted : bool <<get>> <<set>>
    + DeletedBy : Guid? <<get>> <<set>>
    + DeletedOn : DateTime? <<get>> <<set>>
}
class "List`1"<T> {
}
Comment --> "Id" Guid
Comment --> "CreatedBy" Guid
Comment --> "CreatedOn" DateTime
Comment --> "Reactions<CommentReaction>" "List`1"
Comment --> "ProposedMapping" ProposedMapping
Comment --> "Release" Release
Comment --> "Parent" Comment
Comment --> "Children<Comment>" "List`1"
@enduml
