@startuml
class VersionedComponent {
}
class "List`1"<T> {
}
VersionedComponent --> "Id" Guid
VersionedComponent --> "GameVersion" GameVersion
VersionedComponent --> "CreatedBy" Guid
VersionedComponent --> "CreatedOn" DateTime
VersionedComponent --> "Component" Component
VersionedComponent --> "Metadata" MetadataBase
VersionedComponent --> "Mappings<CommittedMapping>" "List`1"
VersionedComponent --> "Proposals<ProposedMapping>" "List`1"
VersionedComponent --> "LockedMappingTypes<LockingEntry>" "List`1"
@enduml
