@startuml
class VotingRecord {
    + IsForVote : bool <<get>> <<set>>
    + HasBeenRescinded : bool <<get>> <<set>>
}
VotingRecord --> "Id" Guid
VotingRecord --> "Proposal" ProposedMapping
VotingRecord --> "CreatedOn" DateTime
VotingRecord --> "VotedBy" Guid
@enduml
