version: '3.8'

services:
  db_data:
    image: postgres:13
    networks:
      - modmappings-data
    environment:
      - POSTGRES_DB=mmms
      - POSTGRES_USER=mmms
      - POSTGRES_PASSWORD=mmms
    volumes:
      - /var/docker/data:/var/lib/postgresql/data
    deploy:
      placement:
        constraints:
          - node.labels.type==worker
          - node.labels.system==production
          - node.labels.usecase==modmappings

  identity-server:
    image: modmappings/docker-wso2-is:5.11.0
    deploy:
      placement:
        constraints:
          - node.labels.type==worker
          - node.labels.system==production
          - node.labels.usecase==modmappings
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.modmappings-auth2-http.rule=Host(`dev.auth.modmappings.org`)
        - traefik.http.routers.modmappings-auth2-http.entrypoints=http
        - traefik.http.routers.modmappings-auth2-http.middlewares=https-redirect
        - traefik.http.routers.modmappings-auth2-https.rule=Host(`dev.auth.modmappings.org`)
        - traefik.http.routers.modmappings-auth2-https.entrypoints=https
        - traefik.http.routers.modmappings-auth2-https.tls=true
        - traefik.http.routers.modmappings-auth2-https.service=modmappings-auth2
        - traefik.http.routers.modmappings-auth2-https.tls.certresolver=le
        - traefik.http.services.modmappings-auth2.loadbalancer.server.port=9443
        - traefik.http.services.modmappings-auth2.loadbalancer.server.scheme=https
    volumes:
      - /var/docker/wso2/conf/identity-server:/wso2-config-volume
      - /var/docker/wso2/data/identity-server:/wso2is-5.11.0/repository/database
    networks:
      - traefik-public

  apiserver:
    image: container.ldtteam.com/modmappings/api:dev
    environment:
      SPRING_CACHING_REDIS_HOST: tasks.redis
      SPRING_R2DBC_NAME: mmms
      SPRING_R2DBC_URL: r2dbc:postgresql://tasks.db_data/mmms
      SPRING_R2DBC_USERNAME: mmms
      SPRING_R2DBC_PASSWORD: mmms
      SPRING_R2DBC_INITIALIZATIONMODE: ALWAYS
      SPRING_R2DBC_POOL_MAX-SIZE: 20
      SPRING_R2DBC_POOL_INITIAL-SIZE: 20
      SPRING_DATA_POSTGRES_HOST: tasks.db_data
      SPRING_DATA_POSTGRES_PORT: 5432
      SPRING_DATA_POSTGRES_DATABASE: mmms
      SPRING_DATA_POSTGRES_USERNAME: mmms
      SPRING_DATA_POSTGRES_PASSWORD: mmms
      SPRING_SECURITY_TARGET_HOST: https://dev.auth.modmappings.org
      SPRING_URL: https://dev.api.modmappings.org/
      SPRINGDOC.SHOW-ACTUATOR: 'true'
    deploy:
      placement:
        constraints:
          - node.labels.type==worker
          - node.labels.system==production
          - node.labels.usecase==modmappings
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.docker.network=traefik-public
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        - traefik.http.routers.modmappings-api-http.rule=Host(`dev.api.modmappings.org`)
        - traefik.http.routers.modmappings-api-http.entrypoints=http
        - traefik.http.routers.modmappings-api-http.middlewares=https-redirect
        - traefik.http.routers.modmappings-api-https.rule=Host(`dev.api.modmappings.org`)
        - traefik.http.routers.modmappings-api-https.entrypoints=https
        - traefik.http.routers.modmappings-api-https.tls=true
        - traefik.http.routers.modmappings-api-https.service=modmappings-api
        - traefik.http.routers.modmappings-api-https.tls.certresolver=le
        - traefik.http.services.modmappings-api.loadbalancer.server.port=8080
    networks:
      - traefik-public
      - modmappings-data

  ccs:
    image: container.ldtteam.com/modmappings/ccs:dev
    command: bin/CrispyComputingMachine importMinecraftVersionsJob
    environment:
      SPRING_R2DBC_NAME: mmms
      SPRING_R2DBC_URL: r2dbc:postgresql://tasks.db_data/mmms
      SPRING_R2DBC_USERNAME: mmms
      SPRING_R2DBC_PASSWORD: mmms
      SPRING_R2DBC_INITIALIZATIONMODE: ALWAYS
      SPRING_R2DBC_POOL_MAX-SIZE: 20
      SPRING_R2DBC_POOL_INITIAL-SIZE: 20
    deploy:
      placement:
        constraints:
          - node.labels.type==worker
          - node.labels.system==production
          - node.labels.usecase==modmappings
    networks:
      - modmappings-data

  redis:
    image: redis:alpine
    deploy:
      placement:
        constraints:
          - node.labels.type==worker
          - node.labels.system==production
          - node.labels.usecase==modmappings
    networks:
      - modmappings-data

networks:
  traefik-public:
    external: true
  modmappings-data: