version: '2'

services:
  postgres:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - postgresdb:/var/lib/postgresql/data
      - ./dbinitscripts/:/docker-entrypoint-initdb.d/
    network_mode: bridge
  keycloak:
    image: jboss/keycloak:10.0.2
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_FRONTEND_URL: https://auth.modmappings.org/auth
      PROXY_ADDRESS_FORWARDING: 'true'
    network_mode: bridge
    links:
      - postgres
    depends_on:
      - postgres
    labels:
      traefik.enable: 'true'
      traefik.docker.network: mmms_default
      traefik.http.services.mmmskeycloaksrv.loadbalancer.server.port: 8080
      traefik.http.services.mmmskeycloaksrv.loadbalancer.server.scheme: http
      traefik.http.routers.mmmskeycloak.entrypoints: 'websecure'
      traefik.http.routers.mmmskeycloak.rule: 'Host(`auth.modmappings.org`)'
      traefik.http.routers.mmmskeycloak.tls.certresolver: 'forge'
  apiserver:
    build:
      context: .
      dockerfile: Dockerfile-mmms
    image: mmmsapi
    restart: unless-stopped
    network_mode: bridge
    depends_on:
      - postgres
      - keycloak
    links:
      - postgres
    environment:
      SPRING_R2DBC_NAME: mmms
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/mmms
      SPRING_R2DBC_USERNAME: mmms
      SPRING_R2DBC_PASSWORD: mmms
      SPRING_R2DBC_INITIALIZATIONMODE: ALWAYS
      SPRING_R2DBC_POOL_MAX-SIZE: 20
      SPRING_R2DBC_POOL_INITIAL-SIZE: 20
      SPRING_DATA_POSTGRES_HOST: postgres
      SPRING_DATA_POSTGRES_PORT: 5432
      SPRING_DATA_POSTGRES_DATABASE: mmms
      SPRING_DATA_POSTGRES_USERNAME: mmms
      SPRING_DATA_POSTGRES_PASSWORD: mmms
      SPRING_SECURITY_TARGET_HOST: https://auth.modmappings.org
      SPRING_SECURITY_TARGET_REALM: ModMappings
      SPRING_URL: https://api.modmappings.org/
      SPRINGDOC.SHOW-ACTUATOR: 'true'
    labels:
      traefik.enable: 'true'
      traefik.docker.network: mmms_default
      traefik.http.services.mmmsapisrv.loadbalancer.server.port: 8080
      traefik.http.services.mmmsapisrv.loadbalancer.server.scheme: http
      traefik.http.routers.mmmsapi.entrypoints: 'websecure'
      traefik.http.routers.mmmsapi.rule: 'Host(`api.modmappings.org`)'
      traefik.http.routers.mmmsapi.tls.certresolver: 'forge'

volumes: 
  postgresdb:
    driver: local
