@startuml
class ClassMetadata {
}
class "List`1"<T> {
}
MetadataBase <|-- ClassMetadata
ClassMetadata --> "Outer" ClassMetadata
ClassMetadata --> "InnerClasses<ClassMetadata>" "List`1"
ClassMetadata --> "InheritsFrom<ClassMetadata>" "List`1"
ClassMetadata --> "IsInheritedBy<ClassMetadata>" "List`1"
ClassMetadata --> "Package" PackageMetadata
ClassMetadata --> "Methods<MethodMetadata>" "List`1"
ClassMetadata --> "Fields<FieldMetadata>" "List`1"
@enduml
