@startuml
abstract class MappingBase {
    + InputMapping : string <<get>> <<set>>
    + OutputMapping : string <<get>> <<set>>
    + Documentation : string <<get>> <<set>>
}
MappingBase --> "Id" Guid
MappingBase --> "VersionedComponent" VersionedComponent
MappingBase --> "CreatedOn" DateTime
MappingBase --> "CreatedBy" Guid
MappingBase --> "Distribution" Distribution
MappingBase --> "MappingType" MappingType
@enduml
