@startuml
class Component {
}
class "List`1"<T> {
}
Component --> "Id" Guid
Component --> "Type" ComponentType
Component --> "CreatedOn" DateTime
Component --> "CreatedBy" Guid
Component --> "VersionedComponents<VersionedComponent>" "List`1"
@enduml
