@startuml
class Release {
    + Name : string <<get>> <<set>>
    + IsSnapshot : bool <<get>> <<set>> = false
}
class "List`1"<T> {
}
Release --> "Id" Guid
Release --> "CreatedOn" DateTime
Release --> "CreatedBy" Guid
Release --> "GameVersion" GameVersion
Release --> "MappingType" MappingType
Release --> "Components<ReleaseComponent>" "List`1"
Release --> "Comments<Comment>" "List`1"
@enduml
